### ISSUE TITLE
字幕看起來好像沒更新 繁體的字幕少了很多行

### ISSUE THREAD

**Issue by husk0808** [Nekomoekissaten-SUB/Uchiage-Hanabi#1]
字幕看起來好像沒更新 繁體的字幕少了很多行

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-poi-Subs/commit/6fee793cedd7deb677ffd404a062548c930fbdf1
